development:
  adapter: postgresql
  host: 127.0.0.1
  database: <%= Figaro.env.db_name %>
  username: <%= Figaro.env.db_user %>
  password: <%= Figaro.env.db_password %>
  timeout: 10000

test:
  adapter: postgresql
  host: 127.0.0.1
  database: <%= Figaro.env.db_name %>
  username: <%= Figaro.env.db_user %>
  password: <%= Figaro.env.db_password %>
  timeout: 10000

production:
  adapter: postgresql
  host: 127.0.0.1
  database: <%= Figaro.env.fetch("db_name", "") %>
  username: <%= Figaro.env.fetch("db_user", "") %>
  password: <%= Figaro.env.fetch("db_password", "") %>
  timeout: 10000